"""Render ToolHive deployment manifests from a ServerPlan.

Pipeline stage: rendering (plan -> YAML strings).
Produces Kubernetes-style manifests for deploying a generated MCP server
on ToolHive:

    - MCPServer CRD — always generated
    - Ingress — always generated (external access)
    - MCPExternalAuthConfig CRD — only when auth is configured
    - Secret template — only when auth type is api_key (bearerToken)

Each render_* function returns a YAML string. The convenience function
render_manifests() returns a dict mapping filenames to content, handling
the conditional logic for auth-dependent manifests.

Reading guide:
    render_manifests() is the entry point called by cli.run_pipeline().
    The three render_* functions are the leaf renderers.
    Templates live in renderers/templates/*.yaml.jinja2.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from urllib.parse import urlparse

from jinja2 import Environment, FileSystemLoader

from mcp_builder.codegen.plan import ServerPlan

logger = logging.getLogger(__name__)

TOOLHIVE_API_VERSION = "toolhive.stacklok.dev/v1alpha1"
DEFAULT_NAMESPACE = "toolhive-system"

_TEMPLATES_DIR = Path(__file__).parent / "templates"
_env = Environment(  # nosec B701 — generating YAML manifests, not HTML
    loader=FileSystemLoader(_TEMPLATES_DIR),
    keep_trailing_newline=True,
    trim_blocks=True,
    lstrip_blocks=True,
)


def render_manifests(plan: ServerPlan) -> dict[str, str]:
    """Render all deployment manifests as a filename -> content mapping.

    Pipeline stage: rendering (plan -> {filename: YAML string}).
    Called by: cli.run_pipeline().

    Returns a dict with 2-4 entries depending on auth type:
        - "mcpserver.yaml" — always present
        - "ingress.yaml" — always present
        - "mcpexternalauthconfig.yaml" — present when auth.type != "none"
        - "secret.yaml" — present only when auth.type == "api_key"
    """
    logger.info("Rendering deployment manifests for '%s'", plan.server_name)

    manifests: dict[str, str] = {
        "mcpserver.yaml": render_mcpserver(plan),
        "ingress.yaml": render_ingress(plan),
    }

    if plan.auth.type != "none":
        manifests["mcpexternalauthconfig.yaml"] = render_external_auth_config(plan)

    if plan.auth.type == "api_key":
        manifests["secret.yaml"] = render_secret(plan)

    logger.info("Generated %d manifest(s)", len(manifests))
    return manifests


# ---------------------------------------------------------------------------
# Individual manifest renderers
# ---------------------------------------------------------------------------


def render_mcpserver(plan: ServerPlan) -> str:
    """Render the MCPServer CRD manifest."""
    logger.debug(
        "Rendering MCPServer for '%s' (auth=%s)", plan.server_name, plan.auth.type
    )
    tmpl = _env.get_template("mcpserver.yaml.jinja2")
    return tmpl.render(
        server_name=plan.server_name,
        api_version=TOOLHIVE_API_VERSION,
        namespace=DEFAULT_NAMESPACE,
        has_auth=plan.auth.type != "none",
        auth_type=plan.auth.type,
    )


def render_external_auth_config(plan: ServerPlan) -> str:
    """Render the MCPExternalAuthConfig CRD manifest.

    For oauth_bearer: type=embeddedAuthServer with upstream OIDC provider.
    For api_key: type=bearerToken with a tokenSecretRef pointing to a K8s Secret.

    Raises ValueError if called with auth.type == "none" (programming error).
    """
    if plan.auth.type == "none":
        raise ValueError("No auth config to render when auth.type is 'none'")

    if plan.auth.type == "oauth_bearer":
        logger.debug("Rendering embedded auth server config for '%s'", plan.server_name)
        return _render_embedded_auth_server(plan)

    if plan.auth.type == "api_key":
        logger.debug("Rendering bearer token auth config for '%s'", plan.server_name)
        return _render_bearer_token_auth(plan)

    raise ValueError(f"Unexpected auth type: {plan.auth.type!r}")


def render_secret(plan: ServerPlan) -> str:
    """Render the K8s Secret template for bearerToken auth.

    Only generated for api_key auth. OAuth auth does not need a
    user-provided secret — signing keys are auto-generated by ToolHive
    at runtime.

    Raises ValueError if called with a non-api_key auth type.
    """
    if plan.auth.type != "api_key":
        raise ValueError(
            f"Secret template is only for api_key auth, got {plan.auth.type!r}"
        )

    logger.debug("Rendering Secret template for '%s'", plan.server_name)
    tmpl = _env.get_template("secret.yaml.jinja2")
    return tmpl.render(
        server_name=plan.server_name,
        namespace=DEFAULT_NAMESPACE,
    )


def render_ingress(plan: ServerPlan) -> str:
    """Render the Kubernetes Ingress manifest for external access."""
    logger.debug("Rendering Ingress for '%s'", plan.server_name)
    tmpl = _env.get_template("ingress.yaml.jinja2")
    return tmpl.render(
        server_name=plan.server_name,
        namespace=DEFAULT_NAMESPACE,
    )


# ---------------------------------------------------------------------------
# Auth-type-specific renderers
# ---------------------------------------------------------------------------


def _render_embedded_auth_server(plan: ServerPlan) -> str:
    """Render MCPExternalAuthConfig for OAuth (embeddedAuthServer type).

    Generates an OIDC upstream provider config using the issuer and scopes
    from the plan. The user must fill in clientId before applying.
    """
    provider_name = _derive_provider_name(plan.auth.issuer or "upstream")
    issuer_url = plan.auth.issuer or "https://REPLACE_ME"
    # Ensure openid and email scopes are always present for user identity.
    required_scopes = ["openid", "email"]
    raw_scopes = list(plan.auth.scopes or [])
    scopes = required_scopes + [s for s in raw_scopes if s not in required_scopes]

    tmpl = _env.get_template("authconfig_embedded.yaml.jinja2")
    return tmpl.render(
        server_name=plan.server_name,
        api_version=TOOLHIVE_API_VERSION,
        namespace=DEFAULT_NAMESPACE,
        provider_name=provider_name,
        issuer_url=issuer_url,
        scopes=scopes,
    )


def _render_bearer_token_auth(plan: ServerPlan) -> str:
    """Render MCPExternalAuthConfig for API key (bearerToken type)."""
    tmpl = _env.get_template("authconfig_bearer.yaml.jinja2")
    return tmpl.render(
        server_name=plan.server_name,
        api_version=TOOLHIVE_API_VERSION,
        namespace=DEFAULT_NAMESPACE,
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _derive_provider_name(issuer: str) -> str:
    """Derive a short provider name from an OAuth issuer URL.

    Extracts the domain and picks a recognizable short name when possible.
    Falls back to the second-level domain label.

    Examples:
        "https://accounts.google.com" -> "google"
        "https://login.microsoftonline.com/..." -> "microsoft"
        "https://auth.atlassian.com/..." -> "atlassian"
        "https://my-company.okta.com" -> "okta"
        "https://github.com/login/oauth" -> "github"
    """
    try:
        hostname = urlparse(issuer).hostname or issuer
    except Exception:
        hostname = issuer

    # Known provider patterns
    known: list[tuple[str, str]] = [
        ("google", "google"),
        ("microsoft", "microsoft"),
        ("okta", "okta"),
        ("auth0", "auth0"),
        ("atlassian", "atlassian"),
        ("github", "github"),
        ("gitlab", "gitlab"),
        ("slack", "slack"),
        ("amazon", "amazon"),
        ("apple", "apple"),
    ]
    hostname_lower = hostname.lower()
    for pattern, name in known:
        if pattern in hostname_lower:
            logger.debug("Matched known provider '%s' from issuer '%s'", name, issuer)
            return name

    # Fall back to second-level domain (e.g., "example" from "sso.example.com")
    parts = hostname_lower.split(".")
    if len(parts) >= 2:
        fallback = re.sub(r"[^a-z0-9-]", "", parts[-2])
        logger.info(
            "No known provider matched for issuer '%s'; using domain label '%s'",
            issuer,
            fallback,
        )
        return fallback

    logger.warning(
        "Could not derive provider name from issuer '%s'; using 'upstream'", issuer
    )
    return "upstream"
